[0143af8499cacfe5787ad3902a714bbdab4c8b28]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"

[f72908c94df9a256422790d4e2a60c9c33a35f2d]
ac = "libs"
ac_section = "03-filenames_plain1"
ac_pattern = "lib/"

[0ec13430c583830cc4d29640787e2d154b140e31]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet6/"

[8f496952e3e6cdd531675a44b84b3f1954532afb]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[a9227954b0f01e950cc51d744af27585778ddf84]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[1e74951b6cd8132ae417177336b7180e174a5e3f]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[ff6abfec807e31301e3bf9c0df14a22bb6bc3443]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[3e13aae0d1f1a28352d52e41d6ef8f02efd9150e]
ac = "tests"
ac_section = "03-filenames_plain1"
ac_pattern = "tests/"
