[0143af8499cacfe5787ad3902a714bbdab4c8b28]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"

[f72908c94df9a256422790d4e2a60c9c33a35f2d]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[0ec13430c583830cc4d29640787e2d154b140e31]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet6/"

[8f496952e3e6cdd531675a44b84b3f1954532afb]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[a9227954b0f01e950cc51d744af27585778ddf84]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[1e74951b6cd8132ae417177336b7180e174a5e3f]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[ff6abfec807e31301e3bf9c0df14a22bb6bc3443]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[3e13aae0d1f1a28352d52e41d6ef8f02efd9150e]
mc = "tests"

[88b8b7f0c4e9948667a2279e78e975a784049cba]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "crypto/openssl/"

[d9cc3d558d00ee7f62dbef2032f099033c91d2a1]
mc = "contrib"

[f586fc0cf8ff54393a3db565437788a12bdc6e99]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "libexec/"

[42441d342071767f32cfe507466135dc79052a56]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netpfil/"

[99475087d63b4602a0213645bc17d82c3946e2fd]
ac = "network"
ac_section = "05-summary-prefix"
ac_pattern = "^pf:"

[5953e7c98427e038500221e885dffa181dcc064b]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "libexec/"

[3aac05f56620712744cb57d71a0ef42f8d8e3b52]
ac = "userland"
ac_section = "03-filenames_plain1"
ac_pattern = "bin/"

[a5f14e4f9069a8ffed66d923bb0ecf20d8a0e6af]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "contrib/"
g = "tzcode: Use -00 only for invalid time zones-00"

[23e69b54973fcb68d14986ec1600d9dfd0cb7af3]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[60be0d71daab4247dc61c323777b0c593eb76975]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[0f455824d0abdcf09d2e96cf97f99c542bbde877]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64/vmm-00"

[f38792ffc2db67ca82026eb4861f37fe7ac7c38e]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64/vmm-00"

[b3d30be6ed7108b97ed628f7ec9497a112d49fd6]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64/vmm-00"

[e38e04a0ba3fdcdc2f3238bf4d962f65fadf527f]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[0efa0fe26b9d980b2862bb58f8484f0123cff19f]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm/"

[fbe076b2c837f396f96d4725a43745e741557df1]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[fe1d344bf416aa921b4bf233668dda7cf4e27444]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[ab17974c12033c6ff3bae27458efcd13584438ba]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[43bbecaeb95fe5ea1d7acffab4f2874247ba6915]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[749a9266982b8e012b5ec370b2fdfef11f34c0b2]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[38f6a4467419f5b2344d184baa454c126e2919a9]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"
g = "blackhole.4: Describe better-00"

[874eaa3821dd678ca27706af3f023844e3094b2e]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "usr.sbin/.*/tests/.*"

[f221f410920df17a2044cd47a23a6f2a1268b44a]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "usr.sbin/.*/tests/.*"

[d5a5975f8430b15d3b40e4c54214701106b23b83]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[155290b23f0b503b9db675d6a45f85b189ee1926]
mc = "contrib"

[7ece602e00e85195fc426a2401c49921cd39735e]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[5efd371bba1508ed94faed2afbd11936f5fe4dac]
ac = "build"
ac_section = "05-summary-prefix"
ac_pattern = "^packages:"
ah = 1

[2e45f207652842f03101d250d6e542e5e89b6e4a]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[eb373ef459cd87dd9fcab63dc72f3e53c7493758]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[ef4b08a7ed17b84b7d9c5b1dd4781bf4d90f90df]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[67c3c3a274468d09925af3cf64da3f9cf878cc80]
ac = "libs"
ac_section = "05-summary-prefix"
ac_pattern = "^lib.*:"
ah = 1

[61ca69110f2676b7dd3c7ff8dea899615d341e1e]
ac = "build"
ac_section = "05-summary-prefix"
ac_pattern = "^packages:"
ah = 1

[f6d1cdabdd6fe5b26bda58348647d891ad138471]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[ab50101456cded4c9d86065dd59d91c601445d91]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[49e44e06d1ade850cff5e84bf8c5fc425e4411c8]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[9f8114a6d8cb781f155273ef173c29648a1013e6]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[723445fdeee741750a9a3fbd116b540bf605d93a]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[33ceb31e256e386da5a42cc7ca2ef8d4b81b6eda]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[b1f96169cfb50a7b65aee115b2c9ad2f00797bbf]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[ba05cddcc634ac235beb252bd505deb83dcd99f1]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[22886d3af0657dae3b547b21e612642bb47e0321]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[185c2c3dab3627bac929143795cec2d78d0aceab]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[21d42c8d902235b90b59d1aea6203b12e40c6c1b]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[f259daa708f507d3ff450d2eb8c05065674339ec]
mc = "build"
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[8654315ae8d368ce47232bde1f2593e256224e56]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[5bb96dab061af5f44e6090831f1b2724196828b8]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[aba986215fc99d09655d4dcfc5e37f8b1ac83edf]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[3f5385beeacf49d0edb563ccc712841bcfd6b158]
ac = "build"
ac_section = "05-summary-prefix"
ac_pattern = "^release:"

[4422265c67b8a4e19da08fdf5504a7b5e278f815]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[dc0cf0648c8d28ab4914c798a4cff8256ae94ee5]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netpfil/"

[7ec06143964a949ebf6885ac120fdf839ad29eab]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netpfil/"

[f9a71840d8ee0cfff4ec983a589be53648e7017d]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"
g = "blackhole.4: Describe better-00"

[1a9ec72022ddce0cacb9aedda3d69aa95cd45ed0]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[14cc3e658c4ccc382139732b00d5976070300adf]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[86114bae092bd023165e5b9df244fc0849172429]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[50ee990e1874d6d40b8e3dc359c37e2ef2ebf477]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/amd64/"

[a319696875451229f492b6c15e58a0ac54dbcda1]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/amd64/"

[2f031534d1347816a7889674b363975d181f8449]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[57d5a8feda3fd25a650eaab5998db13633d62d2d]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netgraph/"

[2352b89d2f732e3fa33fbd494267f0d4cb917e51]
ac = "admin"
ac_section = "05-summary-prefix"
ac_pattern = "^nanobsd:"

[014647a30ff4c76a99962ee6b079db0d9cdf5949]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[c7a4cdd09f462922510c24dc49010b1c603c3c1a]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[d466cb731a2317ec91a89684e9d6a915fdfcc2ff]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[275f61111f43507a01eef064efc660f1fa72b6a9]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[113e60742ef6ba5c069aa737ee57ba3c2f88b248]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[56e01d0d7e0f7c2129c05467ca99d5f5538f52bc]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[186e433300fed9093dd9716baa20e838eb3b51b6]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[e43fbf27976df17991d32c72c41e43fda66fb262]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[b00e65ff70a4613b3bf2fd2781d174fa437fbfbe]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[b0091036f7240ab244e86a087b18459185a260de]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[a15f2c5cc58f403407daf797a2e6963adffa6c2c]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[f4f0308440d2321fa9172dab1029f16a70289e4e]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[af922319e8136a818bc6c38440d98a574c5df7a9]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netpfil/"

[8821216727043dde9cb23a66b884f7918c80063c]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[8a4386142d05d34a0f8fdce9b4dc2bf5fcfacf8b]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "sbin/.*/tests/.*"

[b7ff11b380bf6ffaa5181596766e2f21a1eec962]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[d3b73a944b11311b8428f30b019802ebe7aeaef8]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[b9d652bb75ffa0945a3bebf68d6d82de26efd269]
ac = "network"
ac_section = "05-summary-prefix"
ac_pattern = "^pf:"

[59f3838b0a942b44397063ffb63a4e4d569129f1]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[2be46b52f5db0630550ec60ad8f92a7e7d7d78ab]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[de8af57c6f4155caa540a68387fdb02514d7e815]
mc = "network"
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[cc97633b4b7a3b670d6223b1cd79a0d807dcebbd]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[ceff35a3aeef822976bd159c8bc403b68d5571ff]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[c913959e9e03ccc979caacda520568c084714f48]
ac = "tests"
ac_section = "03-filenames_plain1"
ac_pattern = "tests/"

[2c53e251601c1fcd558f42a16f6030ba75b7e8df]
ac = "tests"
ac_section = "03-filenames_plain1"
ac_pattern = "tests/"

[64bfb82f17417660f3d1a2d10b381b293b780b21]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[08fbad1b135b0efcfc82f793999463def9f95610]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "sbin/"

[b84666f798e872efd356c5743640e3683ab82f9d]
ac = "network"
ac_section = "05-summary-prefix"
ac_pattern = "^pf:"

[4227d51b6e09ceaaae0f5832c85ec700d80ef18f]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[904ac13eed05fa6153393d692f8ecd45b5dabe11]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[e05521121f05a1b1e0d7c7b5fbe79f83fc303cd0]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netgraph/"

[34ec8c9ccaa473d2d0c177a92c041bb8fdb083db]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[ace98a8fb8fe18d47ccbb55619a9ffd4ac10f98c]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[40417930f6ba50f61990fb995dd071c6fd42d080]
ac = "style"
ac_section = "01-style"
ac_pattern = "[wW]hitespace"

[db37256ce5437e6c667a537afff0fd9f59576514]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[791fc275dbc37ccb3cd4d33a087b69e399019572]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[31d00ac6c9ec342312ca4075d2e6dc0a68b5263d]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[72bf56e273cb914e3b00f98e35e7270efd4edddb]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[cd813380ad832a0bfa5b99f22012092cc9d373b1]
ac = "doc"
ac_section = "03-filenames_plain1"
ac_pattern = "tools/kerneldoc/"

[7e8fb7756c3ed89a2141b923e6da1b6fd96f509c]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[84d688af4e625e159af65cd2432af88609d4962a]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[f15d3694db60d0256d236320fcb9e2c6d871b0a1]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[e194103bd35d9e08a5d271d814d6184ec159eadf]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[495813bfd7a28759b23204d66826ff9b3ee7ab61]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[7feac79331bc8c77e2f8a3e71d6ea087fa17b61d]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[eaf619fddcb21859311b895a0836da3171a01531]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[cee4802d0e2a4f55cecb270f3ab00febe4c220db]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[2554148bd85b172afcc1431df3272f920c82ebce]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[97d152698f4831db5a94d55c15233330c188feda]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = ["sys/dev/", "sys/x86/"]

[9e1e29bd5ec61bba1bb3366ff4c069b0c8f75954]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[5632b0d4628d768c125594a3edee21fb23940067]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[5c0e5f418d9ff68a21d606d62b5fb748b7de229b]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[08f06aa1b4fb6db0d8beb3e1c328b1c1adbec13a]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[01c8e2e33df81b242d73a23de49a6b61f33c24c1]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[7e4c451c12aeb26cc1179221b8230c491b17cf00]
ac = "filesystems"
ac_section = "05-summary-prefix"
ac_pattern = "^vfs:"

[5e395c34402dc3fd5c786168442290a63ff54596]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[523fece9d11e5d084c1d20d10d05971f5354d343]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[ba364342aeef152f3dc486ff3d2ebd4d5a8dd677]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[ceb5792d1e2e58646dd291a2dc3877aaeb73122b]
ac = "build"
ac_section = "03-filenames_plain1"
ac_pattern = "tools/build/"

[d9f03a43f2fec917c31d48b05d751e547c8775c7]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = ["sys/dev/", "sys/x86/"]

[6b164f18118d0e8dbf9826d7117e0e757f7eb727]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[d58339f398748b50ff84421e9d81f8f6d94cb949]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "contrib/"

[df8bc705eb04aff2f718678fffb9d5d4f5d7c223]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"
fc = "contrib"
fc_reason = "Need to be grouped with a5f14e4f9069a8ffed66d923bb0ecf20d8a0e6af"
g = "tzcode: Use -00 only for invalid time zones-00"

[2ed9833791f28e14843ac813f90cb030e45948dc]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[68691160f41bf6ce9ab70ddeeb7eeec2a7bff245]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "libexec/"

[fc726c4ec4636d44e9c964092dba6df07cac8b20]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[29a4fe3dbd8493d0066c5424bfe0e890d4703f34]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[52eb7e394a7e28e9b08e2096c4a085a384cc1dd0]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[f2575d56c8c9a8acad4a61a3586546dff4febce1]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[2872ced18742aaf9480c9a43059cba7e24dd7e59]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "libexec/"

[f34e1c76adc5efd9b603cf6b2d5827f7db8c2ed8]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[9cab9fde5edad9b409dd2317a2aec7815e6d6bed]
ac = "hardware"
ac_section = "05-summary-prefix"
ac_pattern = "^virtual_oss:"
g = "virtual_oss: Port to base-00"

[c457acb4ee821cf015930a94f52c3870786468a7]
ac = "doc"
ac_section = "03-filenames_plain1"
ac_pattern = "RELNOTES"
ah = 1

[5c8835e5c0ce34ee50eba92bb5f4de36139ae7ea]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[202b59c35ead5bd2b71331169bdeb4845cb655c1]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "contrib/"
g = "tzcode: Use -00 only for invalid time zones-00"

[c1d5fc4e0cfc63d23379457ac0b51c59c60b27c7]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[aab45f2aeec803d37514b574010cb5e7cfba8249]
ac = "tests"
ac_section = "03-filenames_plain1"
ac_pattern = "tests/"

[81df9522c8b720016db671c9476fa449bd94e6da]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[bbec2c9a6d9a9b8f6c6edbdd2386dfdcd1c81422]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[70730cd21c9f2b0a80ff07e4491c0fe30f2d87c5]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[86a7787e324b1524abfc434982bae9bf87ad7390]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
fc = "hardware"
fc_reason = "Need to be grouped with 9cab9fde5edad9b409dd2317a2aec7815e6d6bed"
g = "virtual_oss: Port to base-00"

[7e5ab1857817e7be85f012d41239711ef66ebdf6]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"

[938ae26ffda81fd42c235eaa3223dae51331e4eb]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netpfil/"

[6353f5d9a5c6f194bb014b8785a57f5314e8c652]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[7cd3854f827faaad1ecf414d20bdf6802cfa60f8]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netpfil/"

[008d04b297c700ed386a4e846c1834ade7255043]
mc = "internal"
