[55025f42f6fa517aaffc902b3d69fc707536907d]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "stand/"

[b7473a5d68b8ade1ce6c6c08965fe284cc70bd75]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "stand/"

[ebc32e74b6f98a6f2b9ed7cba0078cd64d48701f]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "stand/"

[8d485a8490fe1cd60e7b6a00d3c8a8cc116a56fb]
mc = "contrib"

[69ede18b950e32317d7741410cde7543fa0fce3c]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[d28e4ce6cb61916b4f6bedcf4205a4da1ae121e1]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "contrib/"

[cf76bfbb235116702ea1689bf984f200a72d2790]
ac = "tests"
ac_section = "03-filenames_plain1"
ac_pattern = "lib/libc/tests/"

[c856f327fa6ccf1c5b9e4f531581fa2a0d83c3e0]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[499ff78fb11a5868dfaeaa3fa86ca782b8f06f27]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[6d29d22a9e0c33d1e3e70b8c458982c59b76eb29]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[c7b2e390de43bb2b1a5918a23310ec5464ee3787]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[1ba1c783296bc651e1af3174a1643dff39edf05a]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[87d3ee5d14ba2e912010531e5bb601180bd5803d]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[f487e4778bb7154bec5057f5a6f9ca2a0230d4ae]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[6fa85bf1222672681f6f6bd1502cba752d7c5d5f]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[fc7f27c31eee81c46f20991343799f017aa79948]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[d4fb12583adc0690ae102c47d08598b3dbb06384]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[c392b5a9e44b9c8a0173a4e2c1fb87ee88f4aa3f]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[cfcf1394efb90ff05cd8acce7805145ff93ecac5]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[a16423b7a48c61370d4eeb542e3ca6c1b4c9579a]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[3d76a4feeead2bbda7792a3c4ca534fd4c159721]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[c231e86ce388a0d0fb64e0fd2ff736c990ec97bb]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[721033a7d96f24e80ec18ec9cc17712be55a52b7]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[77098268dc397ea86f157f6e66540cd6618e0a05]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe(4)-00"

[bc48ca42d0d40b0b88df9cc1d8aec49533529690]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[e5ce2d39368f702cc910e3baf103df0a6e1f9266]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "contrib/"

[3203b1a110c890e7b407a83fa3d65b4ba711e59d]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[a02f38ccedc2c648d57fb6e575723b0b31b67ea0]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[6cb542e31bef5fe6e3867b4cfb608f4caeef076d]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/net/"

[c341048373ac6d4bad6dccc63880ff3f326ba15f]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe-00"

[35b883ccf36521a46ba1cd959c144328cce223c5]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe-00"

[19d9a9b15178ed7cfe3f463f43e28cce13fc4f94]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe-00"

[8bc9d3089314635572accfe31a4a56afcc299bab]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[4f272a5ef3d8073940e7719401d1e8de2de6100a]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe-01"

[6154961e2e4c7e1d998f4c9e22c5370d17edb160]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe-01"

[5b9dc22c91068e206fb6cc18ee0cef27067223df]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe-01"

[1e9849415ff9ed958d63bc7e5128c39e991933d2]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe TOE TLS-00"

[7de77bea2a6136af55fdf9cc49fb5b6e7cb9615e]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe TOE TLS-00"

[e2fae07e093bf4953ad7359b2aa9ca62b0d76adf]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "cxgbe TOE TLS-00"

[96054b97b418d1ff2b781e9e23cc86a79d91909a]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[96469647bce10132408db9b436dae8941356453b]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[9e269eafebfca6c876be76a78e4bda621a921e45]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[0532cd2d771372d3266b97aebf4043d5b31b64bd]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[307929b211e07f91260105211b57678e906327af]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "libexec/"

[1060684b04b0ee1e07c6c91f7c52978835ff676a]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "libexec/"

[e02003bce726333872d65b7b9a1557d97b6d91a0]
ac = "network"
ac_section = "05-summary-prefix"
ac_pattern = "openssh:"

[d4cbdd9ad04ab1d68046b62541b2a487e6df077e]
ac = "internal"
ac_section = "03-filenames_plain1"
ac_pattern = "share/misc/committers-ports.dot"

[59fc2b0166f71c791113379d16b8cef7039f289d]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "contrib/"

[c5a813c9f486da49551c3be2e7700ca0cb0a489a]
mc = "filesystems"

[9f269a0a771aff4f0a735211907a52c52fc0661b]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"
g = "MAC/do: Check executable path from the current jail's root-00"

[05e5de00b9ea048f868522ff0bdae4e388685ddf]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
fc = "kernel"
fc_reason = "Need to be grouped with 9f269a0a771aff4f0a735211907a52c52fc0661b"
g = "MAC/do: Check executable path from the current jail's root-00"

[3ca1e69028acdee30739c0e0856692395a36fd21]
ac = "userland"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.bin/"
ah = 1

[c87a9f51a0debf707cb4fc9a5e3b4425b08d154d]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
fc = "kernel"
fc_reason = "Need to be grouped with 05e5de00b9ea048f868522ff0bdae4e388685ddf"
g = "MAC/do: Check executable path from the current jail's root-00"

[17be686a39a07958f61e42c4b5c797bb1d1e9895]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[4e7a375804e5ad4b244ce9a035fa971cbf2f0944]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"
g = "revert-pair-IfAPI-00"

[614c8750ce116865953916b8b5bab2467ee94187]
mc = "network"
ah = 1

[eaecc9551ae4d342fee921fb4c0a1eeb6bf68b86]
ac = "build"
ac_section = "05-summary-prefix"
ac_pattern = "packages:"
g = "packages: Add an \"optional\" set-00"

[2c2a2b8281be2f4270fd98eda743a3a8c2f36949]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[123c2dc6e15a62ceba3469caf0f1a6801214a7d3]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"

[4179e6b78297369f0cf0eae1076e01e5151c5cbe]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"

[52ce810302f70cc7b995651eb1b19adfa014b351]
ac = "kernel"
ac_section = "04-filenames_plain2"
ac_pattern = "sys/"
ah = 1

[494de51bc0074472d1b01604f085daea0844f240]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[89eee8ee2ce57b7884defb8f9af016cd28ef1562]
ac = "network"
ac_section = "05-summary-prefix"
ac_pattern = "wlanstat\\(8\\):"

[6952bb321c5cc14168a4f2638a0ce2483cc5149c]
ac = "network"
ac_section = "05-summary-prefix"
ac_pattern = "wlanstat\\(8\\):"

[f1a372ed88b11c1e096523c0b6cf62902c1db37c]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = ["sys/arm/", "sys/arm64/", "sys/dev/"]

[a087b4aec38c37d47b888aa8411948250cdd4bc0]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"
g = "packages: Add an \"optional\" set-00"

[d31e342bcc8e22d7eb25c21a711cd4b8a54db6c0]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
g = "sh: Remove /.profile-00"
ah = 1

[2507698b630db3d88b0aab12c348873f827255a2]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[bb0955ee4db8870bb013cf7d208ad9b2fc27b619]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
g = "sh: Remove /.profile-00"

[b0f25a38d7217b04dcdf7f2272ecf5f2f314d314]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[11709058bf680f5738c6656597f2ff9e662c9400]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[9124ace751eb9c856c50c3698cf93ede45a9897d]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[41ee4321cc528b1f72d6a674fafdd5337be83f95]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[a053f948ade60e8a63ebdaa676bf95c5ce38af07]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[4c8bbf5897b7e8e580f8ecb1d9d93f5d6d6c7f24]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[25d551b5fb1d28ed485d56d9d637993eb2d223b1]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[24e4dcf4ba5e9dedcf89efd358ea3e1fe5867020]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[3cbd1f81688855a91f826ee4e04618ceace101ca]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"

[2ffaca551eaf32c17f701762ecf29a961cf19aa4]
mc = "hardware"
g = "snd_hda: Implement automatic redirection between associations-00"

[fa26e445544eb88f05779258e2ab9c96384fe74d]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "gpioc-00"

[d000adfe41e6f2fe8f3dbe92d8fc2d34ae882086]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "gpioc-00"

[2679636b4412927242e46d3806fbb58e2702eddb]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"
g = "gpioc-00"

[06afa0a55e0acc00823f08fe17305df13502f235]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]
g = "pkgbase: move ncurses into its own package-00"

[5e4e12ae64b3e0377984d22610a6b3d6ccd6cee6]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[2213e158886f72f45f288c94069a9a40c4f334ed]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"

[a57f6ce4792f12bebdbe3e46d6d9d39da10055db]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"

[be8830612314d9afb64b5c040db689de44eb4b85]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[8af6aee96ed609456900c6dd92dafabac5e89c0a]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[aa1afb69dcedfc68859815987c46997500f834c3]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "crypto/openssl/"

[2bdc89535a8837347bb3b523715bba021dea4418]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/amd64/"

[f040ee6e407832fc9f08d85cd792d1cfb8104976]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
g = "virtual_oss: Do not build if WITHOUT_CUSE is set-00"

[6e4b811009d63f33c59d51f28fd4a030ca90843e]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[f45608124286a7e0616d1d23b9506709f10c12fc]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[fb77d8e546e1894300843600409c48596644b3b6]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[df74ea7f41090f38d9fa1c739029b135cd199a45]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = "release/.*"
g = "pkgbase: move ncurses into its own package-00"

[c2900b6e8255ba4f54dbd897cf42427db577ed3d]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[f7aad20db59210a4411559d07976a48809b3b0a7]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[5d8fde850768d31f722de6177204ec7cab199bd1]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[4e0997d1d492eb955bb20a970a7fce189269498c]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/contrib"

[5b63afc09a86318fa8bf09a786a1b084e000cc51]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/dev/"

[5cc36854ee63dc695d90a841d9db587bec67ba24]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
fc = "hardware"
fc_reason = "Need to be grouped with 2ffaca551eaf32c17f701762ecf29a961cf19aa4"
g = "snd_hda: Implement automatic redirection between associations-00"

[7bc6ec1a255da6678a72330d65a1f320de538727]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"

[b5e2bd5ef38181ce4a445ec19f1fa5cb6c8ea692]
ac = "style"
ac_section = "01-style"
ac_pattern = "[sS]tyle"

[bce8cdaf4cb184db577a5633e82bdabe24239af1]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
g = "virtual_oss: Do not build if WITHOUT_CUSE is set-00"

[1bbc898dbf72638ac0dfbc666f62d39dbd68258a]
ac = "contrib"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/contrib"

[cf583997282f962d9e8bf478667d5087f7c1f2da]
ac = "build"
ac_section = "03-filenames_plain1"
ac_pattern = ".github/workflows/"

[bdb205c53ed769ad9f5e8da1ec6d05c48992dbf8]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[e7258c42520c18c034f644b97377d8d2a0ad8b7c]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]

[ebb60d47a5350e5d752b97cba8b3b0c3be8aa1eb]
ac = "reverts"
ac_section = "00-reverts"
ac_pattern = "This reverts commit \\b([0-9a-fA-F]{40})\\b"
g = "revert-pair-IfAPI-00"

[300aa267efaa08564337797e89590737a7cc6af0]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[76157a63a0c63dd7363f6c8ae60edc814b3c138a]
ac = "filesystems"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/ufs/"

[3034fa3d4321fdc487428c9050711de9ce234567]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[e91fc88bca02a74ea972ebf7f66aef3a3298ad54]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[36f2eda251713d4d38f41cf269876b069e3897ff]
ac = "internal"
ac_section = "03-filenames_plain1"
ac_pattern = "ObsoleteFiles.inc"

[d0c8a0b3e6fc5372428eb4fddcd4f8c65b5b0ee0]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"
g = "tests/netinet: extend IPv4 multicast testing framework-00"

[213170eb956fa7eec93c2ab4159d6ed68e8e1b1d]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/net/"

[09cd3decf0fae4b769b04c1e900ed5935c40957e]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[63ce00f5d0b5dc34d57fb8d3969b875732c93eb2]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[ed6716207debca81c37a1399ecf1d799be0e688d]
ac = "admin"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.sbin/"

[1b806e607f52285f973fb1106491668fd28da6a4]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = [".*Makefile", "release/.*"]
ah = 1

[7841b44f8491d69c75207d0f3a1eb34501d99edd]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[e98d3416916cdb6285d4d1807582baf6faa3ddcc]
ac = "style"
ac_section = "01-style"
ac_pattern = "[tT]ypo"

[97d395d91025b5b652f2998c90716c253600dcd1]
ac = "userland"
ac_section = "04-filenames_plain2"
ac_pattern = "usr.bin/"

[90d2aedbb964bb39ecc23e736dc26ff45603562f]
ac = "style"
ac_section = "01-style"
ac_pattern = "[wW]hitespace"

[0a551f8a7d68ca42d60824682123f12bba76c477]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[f7b6ea699b23b3af81866ef3aafb398c2c0d45af]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[5ead817c3b7af6d6b5fea222ab144db2c3167b22]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "libexec/"

[244a5188e7681bf8d98a49c78439df61e6816c93]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netpfil/"

[3b9d89e1c90fd3b2667c07d5a0bfd300bf635bb3]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"

[a733ea831a00d4c0ee4b67824c9ac4e5ba82be08]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"
g = "tests/netinet: extend IPv4 multicast testing framework-00"

[f9fc93690aef7a56f62a051de6231fe2af699728]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet6/"

[c23b64fba9fb9715397a9e6ecbae670ee791dce9]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"

[b7118461f9099876cb2c2923948f8fb647defd57]
ac = "network"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/netinet/"

[2f7a796b590e67c5d123f2b00b3aaf7ba7a32a13]
ac = "build"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*Makefile"
g = "thunderbolt.4: Initial manual for HW Relnotes-00"

[0c1c81c479bef8d3e67f93ea00fc5d34ccf5af33]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[5bba547a678beb280bf4080375f45b04ceb44fc5]
ac = "build"
ac_section = "03-filenames_plain1"
ac_pattern = ".cirrus.yml"

[e2796f0359afad522113c25d720fa30677a044ab]
ac = "build"
ac_section = "03-filenames_plain1"
ac_pattern = ".cirrus.yml"

[e4e412e45a17d2f63f6693d41b274379d108c82f]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"
fc = "build"
fc_reason = "Need to be grouped with 2f7a796b590e67c5d123f2b00b3aaf7ba7a32a13"
g = "thunderbolt.4: Initial manual for HW Relnotes-00"

[7b18bf2a225af348c2d56ad345862fe0f1055839]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"

[c1723bbe2aa7f6c8b23d3aa97379d89e883b0a93]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64/vmm-00"

[35d0c9efb17a9a7fea57c3a4a056141b21dad18f]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64/vmm-00"

[4954ec00c4200d8bfd29875fc13f541942209824]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"
g = "arm64/vmm-00"

[d552556b7e6d226887ebb6da30e4f1dcff3cb407]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[4aa762f3cb97402f0345ce5112c47a303dd4107d]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[c67ea2707d2b5e6deb5986710f520ff69e4f78a3]
ac = "hardware"
ac_section = "03-filenames_plain1"
ac_pattern = "sys/arm64/"

[54b24b9da8be70192b7baaeae8fc26fda6581222]
ac = "tests"
ac_section = "02b-filenames_wildcards2"
ac_pattern = "tests\\/.*"

[e57d72a7f35c3fc80dc9ac744056b2354b1be741]
ac = "internal"
ac_section = "03-filenames_plain1"
ac_pattern = "tools/tools/git/mfc-candidates.lua"

[44f3e9f7f6c9afed33d2967c1ed48361bb6b404b]
ac = "doc"
ac_section = "02-filenames_wildcards"
ac_pattern = ".*\\.[1-9]"
