[55025f42f6fa517aaffc902b3d69fc707536907d]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "stand/"

[b7473a5d68b8ade1ce6c6c08965fe284cc70bd75]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "stand/"

[ebc32e74b6f98a6f2b9ed7cba0078cd64d48701f]
ac = "admin"
ac_section = "03-filenames_plain1"
ac_pattern = "stand/"
