[fc3e8434a61f372b4d6ec6bd8910ac8cd54b9b37]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"

[1c2263b683977ebab3d9a6448268ad810ceeec70]
ac = "libs"
ac_section = "04-filenames_plain2"
ac_pattern = "lib/"
