# The git repository's "commit dates" are not always accurate, so we
# cannot rely on dates for the bounds of each span.  The "date_start" and
# "date_end" are purely for display; the actual spans are defined by
# "start_after" and "end_including".
#
# I'm not wild about "start_after" and "end_including" -- I think it would
# be more natural to have "start_including" and "end_before" -- but that's
# what `git rev-list A..B` does.  As long as the names reflect what the
# system does, it's fine.

[2025-09-01]
date_start = "2025-09-01"
date_end = "2025-09-07"
start_after = "004ce88ad1efd42a1d7d5692849b4aa6906178fc"
end_including = "14b61b2e931741281d0bfef426e9809f16006504"

[2025-09-08]
date_start = "2025-09-08"
date_end = "2025-09-14"
start_after = "14b61b2e931741281d0bfef426e9809f16006504"
end_including = "e779891327b1d9b9ab10ba482e59f498790505a7"

[2025-09-15]
date_start = "2025-09-15"
date_end = "2025-09-21"
start_after = "e779891327b1d9b9ab10ba482e59f498790505a7"
end_including = "6d83ae143b1f598b5f8868508f6e8a7d3440f568"
in_progress = true

[2025-q4-and-sep-emph]
display_name = "2025 Q4+sep, only \"emphasized\" commits"
date_start = "2025-09-01"
date_end = "2025-12-31"
include_spans = [2025-09-01, 2025-09-08, 2025-09-15]
only_show = ["emph"]
in_progress = true
alternate_index = true
